# Makefile
#
# Last update : Tue, 13 Mar 2018, 12:05
#
# This file was auto generated by makegen, an automatic makefile generator.
#
# Repository : https://github.com/reinhardlinardi/makegen
# Maintainer : segfault1001

# Compiler

COMPILER := g++

# Flags

COMPILE_FLAGS := -g -Wall -Isrc
LINKING_FLAGS := 

# Source code

SRC_ROOT := src
SRC_DIRS := $(shell find $(SRC_ROOT) -type d)
SRC_FILES := $(shell find $(SRC_ROOT) -name '*.cpp' -type f)

# Build

OBJ_DIR := bin/obj
EXEC_BINARY_DIR := .
OBJ_FILES := $(addprefix $(OBJ_DIR)/, $(notdir $(patsubst %.cpp, %.o, $(SRC_FILES))))
EXEC_BINARY_NAME := hello_world
EXEC_BINARY := $(EXEC_BINARY_DIR)/$(EXEC_BINARY_NAME)

# Rules

.PHONY : clean
VPATH = $(SRC_DIRS)

$(EXEC_BINARY): $(OBJ_FILES) | $(EXEC_BINARY_DIR)
	@echo "Linking $@ ..."
	@$(COMPILER) -o $@ $^ $(LINKING_FLAGS)

$(EXEC_BINARY_DIR):
	@mkdir -p $@

$(OBJ_DIR)/%.o: %.cpp | $(OBJ_DIR)
	@echo "Compiling $< ..."
	@$(COMPILER) -o $@ -c $< $(COMPILE_FLAGS)

$(OBJ_DIR):
	@mkdir -p $@

clean:
	@echo "Cleaning up ..."
	@rm $(EXEC_BINARY) $(OBJ_DIR)/*.o