# --- Autogenerated by makegen ---

# Source
SRC_ROOT := .
SRC_DIRS := $(shell find $(SRC_ROOT) -type d)
SRC_FILES := $(shell find $(SRC_ROOT) -name '*.cpp' -type f)

# Build
COMPILER := g++
COMPILER_FLAGS := -O2
LINKER_FLAGS := 

# Output
OBJECT_PATH := bin
EXE_PATH := .
EXE_NAME := makegen
OBJECT_FILES := $(addprefix $(OBJECT_PATH)/, $(notdir $(patsubst %.cpp, %.o, $(SRC_FILES))))
EXE_BINARY := $(EXE_PATH)/$(EXE_NAME)

# Rules
.PHONY : clean
VPATH = $(SRC_DIRS)

$(EXE_BINARY): $(OBJECT_FILES) | $(EXE_PATH)
	@echo "Linking   $@ ..."
	@$(COMPILER) -o $@ $^ $(LINKER_FLAGS)

$(EXE_PATH):
	@mkdir -p $@

$(OBJECT_PATH)/%.o: %.cpp | $(OBJECT_PATH)
	@echo "Compiling $< ..."
	@$(COMPILER) -o $@ -c $< $(COMPILER_FLAGS)

$(OBJECT_PATH):
	@mkdir -p $@

clean:
	@echo "Cleaning up ..."
	@rm $(EXE_BINARY) $(OBJECT_PATH)/*.o